window.PORTFOLIO = {
  handle: "orangefatcat",
  status: "Commissions open",

  contact: {
    discordUsername: "orangefatcat1",
    discordUrl: "https://discord.gg/gnKbgBVX3r",
    discordLabel: "Join my studio Discord",
    robloxUrl: "",
    talentHubUrl: "",
    xUrl: "",
    email: "",
  },

  brief: [
    "Hey orangefatcat, I want to commission VFX.",
    "",
    "Game / link:",
    "Number of weapons / effects:",
    "Effects wanted (auras, trails, beams, abilities, impacts):",
    "Theme or references:",
    "Rarity tiers (if any):",
    "Deadline:",
    "Budget:",
  ],

  features: {
    hero: { id: "hero", frames: 24 },
    wall: { id: "wall", frames: 24 },
  },

  work: [
    { id: "s1088", title: "Solar trident", tags: ["Flame"], frames: 24 },
    { id: "s1126", title: "Storm scythe", tags: ["Lightning"], frames: 24 },
    { id: "s1122", title: "Venom blade", tags: ["Smoke"], frames: 24 },
    { id: "s1140", title: "Gilded feather", tags: ["Arcane"], frames: 24 },
    { id: "s1139", title: "Ember fang", tags: ["Flame"], frames: 24 },
    { id: "s50", title: "Void vortex", tags: ["Arcane"], frames: 24 },
    { id: "s1132", title: "Phantom edge", tags: ["Smoke"], frames: 24 },
    { id: "s10020", title: "Toxic neon", tags: ["Flame"], frames: 24 },
    { id: "s35", title: "Crimson core", tags: ["Glow"], frames: 24 },
    { id: "s1175", title: "Frostbite", tags: ["Lightning"], frames: 24 },
    { id: "hammers", title: "Hammer set", tags: ["Sets"], frames: 24 },
    { id: "s1158", title: "Festive cutter", tags: ["Seasonal"], frames: 24 },
    { id: "s1102", title: "Amethyst cleaver", tags: ["Glow"], frames: 24 },
    { id: "s45", title: "Thorn maul", tags: ["Arcane"], frames: 24 },
    { id: "s1007", title: "Reaper rays", tags: ["Glow"], frames: 24 },
    { id: "s1059", title: "Blaze blaster", tags: ["Flame"], frames: 24 },
    { id: "s1061", title: "Arcane blaster", tags: ["Flame"], frames: 24 },
    { id: "s1124", title: "Hex dagger", tags: ["Smoke"], frames: 24 },
  ],

  effects: [
    { id: "fx-rngaura2", title: "Radiant halo aura", tags: ["Auras"], frames: 24 },
    { id: "fx-explosion", title: "Debris explosion", tags: ["Explosions"], frames: 24 },
    { id: "fx-blackhole2", title: "Black hole", tags: ["Abilities"], frames: 24 },
    { id: "fx-aura", title: "Crimson power-up", tags: ["Auras"], frames: 24 },
    { id: "fx-firevortex", title: "Fire vortex", tags: ["Abilities"], frames: 24 },
    { id: "fx-electric", title: "Electric impact", tags: ["Impacts"], frames: 24 },
    { id: "fx-rngaura1", title: "Rune circle aura", tags: ["Auras"], frames: 24 },
    { id: "fx-blackhole", title: "Void rift", tags: ["Abilities"], frames: 24 },
    { id: "fx-redexplosion", title: "Blood burst", tags: ["Explosions"], frames: 24 },
    { id: "fx-rngaura3", title: "Toxic surge aura", tags: ["Auras"], frames: 24 },
    { id: "fx-lightning", title: "Lightning strike", tags: ["Impacts"], frames: 24 },
    { id: "fx-shield", title: "Guard shield", tags: ["Abilities"], frames: 24 },
    { id: "fx-fireaura", title: "Fire aura", tags: ["Auras"], frames: 24 },
    { id: "fx-portal", title: "Warp portal", tags: ["Abilities"], frames: 24 },
    { id: "fx-wateraura", title: "Water aura", tags: ["Auras"], frames: 24 },
  ],
};
